[package]
name = "py_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_client"
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
convex = { path = "../convex" }
convex_sync_types = { path = "../convex/sync_types", version = "=0.5.0" }
derive_more = { workspace = true }
futures = { workspace = true }
imbl = { workspace = true }
parking_lot = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
pyo3 = { workspace = true }
pyo3-asyncio = { version = "0.19", features = ["tokio-runtime"] }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["float_roundtrip", "preserve_order"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["io-util", "sync"] }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

[dev-dependencies]
colored = { workspace = true }
convex_sync_types = { path = "../convex/sync_types", version = "=0.5.0", features = ["testing"] }
dotenvy = { workspace = true }
maplit = { workspace = true }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[features]
default = ["native-tls"]
native-tls = ["tokio-tungstenite/native-tls"]
native-tls-vendored = ["tokio-tungstenite/native-tls-vendored"]
rustls-tls-native-roots = ["tokio-tungstenite/rustls-tls-native-roots"]
rustls-tls-webpki-roots = ["tokio-tungstenite/rustls-tls-webpki-roots"]
testing = ["proptest", "proptest-derive"]
