[package]
name = "py_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_client"
crate-type = ["cdylib"]

[dependencies]
convex = { path = "../convex" }
futures = { workspace = true }
parking_lot = { workspace = true }
pyo3 = { workspace = true }
pyo3-asyncio = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[features]
default = ["native-tls"]
native-tls = ["convex/native-tls"]
native-tls-vendored = ["convex/native-tls-vendored"]
rustls-tls-native-roots = ["convex/rustls-tls-native-roots"]
rustls-tls-webpki-roots = ["convex/rustls-tls-webpki-roots"]
